spring:
  application:
    name: demo-service-prod

logging:
  level:
    root: WARN
    com.example: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: when_authorized
