apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stb

resources:
  - ../../base

namePrefix: stb-

commonLabels:
  environment: stb

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

configMapGenerator:
  - name: demo-service-config
    behavior: replace
    literals:
      - SPRING_PROFILES_ACTIVE=stb
